"""remove refund and deposit in Payment

Revision ID: e22c1f223f2f
Revises: f96bbd3bfdd8
Create Date: 2026-03-09 14:52:39.999825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22c1f223f2f'
down_revision: Union[str, Sequence[str], None] = 'f96bbd3bfdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'refunded_amount')
    op.drop_column('payments', 'deposited_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('deposited_amount', sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column('payments', sa.Column('refunded_amount', sa.NUMERIC(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###
